### ISSUE TITLE
Scraper is broken

### ISSUE THREAD

**Issue by madsnedergaard** [hectorespert/ree#4]
Hi, seems like the scraper is not working as intended any more. 
Perhaps the REE dashboard changed HTML markup or something like that? :) 

Here's what I get when using the example from README:
<img width="843" alt="Screenshot 2022-06-19 at 10 53 33" src="https://user-images.githubusercontent.com/3296643/174473318-d9a47f3a-3441-4096-9e6b-310750f59b27.png">

[Relevant issue on electricityMap](https://github.com/electricitymap/electricitymap-contrib/issues/4239)

**Comment by madsnedergaard** [comment]
Thanks for fixing it, would you mind doing a new release to pypi so we can use the new version on electricityMap? :)

**Comment by hectorespert** [comment]
I would like to create a new release these week or next

**Comment by madsnedergaard** [comment]
Great! 🥳

**Comment by hectorespert** [comment]
Release 2.3.0 is available that fixes scraper
